version: v1.0
name: unit-tests
jobs:
- job: integration
  steps:
  - checkout: '{{.cds.workspace}}'
  - name: Run composer update
    script:
    - php -d memory_limit=-1 /usr/bin/composer update
  - name: Run composer to add ci tools
    script:
    - php -d memory_limit=-1 /usr/bin/composer require --dev phpunit/phpunit pdepend/pdepend
  - name: Create reports dir
    script:
    - mkdir reports
  - name: Run phpunit
    script:
    - php -d memory_limit=-1 {{.cds.workspace}}/vendor/bin/phpunit --log-junit reports/web-phpunit.xml
      --coverage-clover reports/web-clover.xml --coverage-html reports/web-coverage
  - name: Run pdepend
    script:
    - php -d memory_limit=-1 {{.cds.workspace}}/vendor/bin/pdepend --jdepend-xml=reports/jdepend.xml
      src
  - jUnitReport: '{{.cds.workspace}}/reports/web-phpunit.xml'
  - coverage:
      format: clover
      path: '{{.cds.workspace}}/reports/web-clover.xml'
  requirements:
  - binary: bash
  - binary: composer
  - binary: curl
  - binary: git
  - binary: unzip
